# Generated by Django 4.2 on 2023-11-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shredder',
        ),
        migrations.RemoveField(
            model_name='product',
            name='water',
        ),
        migrations.AddField(
            model_name='product',
            name='option',
            field=models.CharField(default='100', max_length=50),
        ),
    ]
