# Generated by Django 4.2 on 2023-11-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_color_remove_product_shredder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='zdjecie',
            field=models.ImageField(default='shop/static/images/default.png', upload_to='shop/static/images/products/'),
        ),
    ]
