# Generated by Django 4.2 on 2023-11-15 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_zdjecie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='zdjecie',
            new_name='photo',
        ),
    ]
