# Generated by Django 4.2 on 2023-11-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_zdjecie_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='shop/static/images/products/'),
        ),
    ]
