# Generated by Django 4.2 on 2023-11-15 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useritem',
            name='height',
        ),
    ]
