# Generated by Django 4.2 on 2023-11-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_useritem_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='option',
            field=models.CharField(default='500g', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='option',
            field=models.CharField(default='500g', max_length=50),
        ),
    ]
