# Generated by Django 4.2 on 2023-11-15 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_useritem_option_alter_product_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useritem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='useritem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='UserItem',
        ),
    ]
