# Generated by Django 4.2 on 2023-11-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_product_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='option',
        ),
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.PositiveBigIntegerField(default=1000),
        ),
    ]
