# Generated by Django 4.2 on 2023-11-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_product_option_product_sold_product_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='odzywki', max_length=20),
        ),
    ]
