# Generated by Django 4.2 on 2023-11-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='flavour',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='usage',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
