# Generated by Django 4.2 on 2023-11-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_composition_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flavour',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
