# Generated by Django 4.2 on 2023-11-23 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_remove_product_category_remove_product_composition_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
