# Generated by Django 4.2 on 2023-11-23 18:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_product_alter_useritem_product_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='images/products/')),
                ('flavour', models.CharField(default=0, max_length=50)),
                ('description', models.CharField(default=0, max_length=2000)),
                ('composition', models.CharField(default=0, max_length=2000)),
                ('usage', models.CharField(default=0, max_length=500)),
                ('storage', models.PositiveBigIntegerField(default=1000)),
                ('sold', models.PositiveBigIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.AlterField(
            model_name='useritem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
