# Generated by Django 4.2 on 2023-12-02 14:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_useritem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useritem',
            name='added',
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='useritem',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.order')),
                ('userItem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.useritem')),
            ],
        ),
    ]
