# Generated by Django 4.2 on 2023-12-02 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_rename_orderitem_orderhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderHistory',
        ),
    ]
