# Generated by Django 4.2 on 2023-12-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_remove_productreview_created_at_productreview_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='review',
            field=models.BooleanField(default=False),
        ),
    ]
