# Generated by Django 4.2 on 2023-12-19 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_orderhistory_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='priceOrder',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
