# Generated by Django 4.2 on 2023-12-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_orderhistory_priceorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='priceOrder',
            field=models.FloatField(default=0),
        ),
    ]
