# Generated by Django 4.2 on 2023-12-21 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_remove_product_storage_productstorage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productstorage',
            old_name='usage',
            new_name='option',
        ),
    ]
