# Generated by Django 4.2 on 2024-01-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0053_alter_orderhistory_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PKWiU',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
