# Generated by Django 4.2 on 2024-01-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0055_productstorage_price_productstorage_priceall_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
    ]
