# Generated by Django 4.2 on 2024-01-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0058_product_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='delivery_status',
            field=models.CharField(choices=[('wysłane', 'Wysłane'), ('dostarczone', 'Dostarczone')], default='Wysłane', max_length=20),
        ),
    ]
