# Generated by Django 4.2 on 2024-01-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0060_alter_orderhistory_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstorage',
            name='storageJanuary',
            field=models.FloatField(default=1000),
        ),
        migrations.AlterField(
            model_name='productstorage',
            name='storage',
            field=models.FloatField(default=1000),
        ),
    ]
