# Generated by Django 4.2 on 2024-01-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0062_monthlyordersummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyordersummary',
            name='month',
            field=models.CharField(max_length=50),
        ),
    ]
