# Generated by Django 4.2 on 2024-01-07 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0063_alter_monthlyordersummary_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyordersummary',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
