# Generated by Django 4.2 on 2024-01-07 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0064_alter_monthlyordersummary_total_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyordersummary',
            name='total_value',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
