# Generated by Django 4.2 on 2024-01-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0065_alter_monthlyordersummary_total_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
