# Generated by Django 4.2 on 2024-01-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0066_alter_productreview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
