# Generated by Django 4.2 on 2024-01-08 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0072_alter_code_code_alter_code_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('product', models.CharField(max_length=200)),
                ('option', models.CharField(max_length=50)),
                ('quantity', models.FloatField()),
            ],
        ),
    ]
