# Generated by Django 4.2 on 2024-01-08 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0073_newdelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdelivery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
