# Generated by Django 4.2 on 2024-01-09 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0075_deliverymethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdelivery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product'),
        ),
        migrations.AlterField(
            model_name='productstorage',
            name='product_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='products.unitproduct'),
        ),
    ]
