# Generated by Django 4.2 on 2024-01-09 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0077_alter_productstorage_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdelivery',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
