# Generated by Django 4.2 on 2024-01-09 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0078_alter_newdelivery_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_method',
        ),
    ]
