# Generated by Django 4.2 on 2024-01-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0080_order_delivery_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='delivery_status',
            field=models.CharField(choices=[('Realizacja', 'Realizacja'), ('Przesłano', 'Przesłano'), ('Doręczono', 'Doręczono')], default='Realizacja', max_length=20),
        ),
    ]
