# Generated by Django 4.2 on 2024-01-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0082_remove_code_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='key',
            field=models.CharField(default=1, max_length=70, unique=True),
        ),
    ]
