# Generated by Django 4.2 on 2024-01-12 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0085_alter_orderhistory_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='key',
            new_name='key_session',
        ),
        migrations.RenameField(
            model_name='orderhistory',
            old_name='key',
            new_name='key_session',
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
