# Generated by Django 4.2 on 2024-01-14 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0087_remove_orderhistory_key_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyordersummary',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
