# Generated by Django 4.2 on 2024-01-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0088_alter_monthlyordersummary_total_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='key',
            field=models.CharField(default=1, max_length=70),
        ),
    ]
