# Generated by Django 4.2 on 2024-01-15 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0092_pkwiu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='PKWiU',
        ),
    ]
