# Generated by Django 4.2 on 2024-03-09 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0097_remove_productempty_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductEmpty',
        ),
    ]
