# Generated by Django 4.2 on 2024-03-09 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0099_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstorage',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='products.warehouse'),
        ),
    ]
