# Generated by Django 4.2 on 2024-01-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_video_desctiption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='desctiption',
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(default='opis'),
        ),
    ]
