# Generated by Django 4.2 on 2024-01-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_remove_video_desctiption_video_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='ćwiczenia', max_length=100),
        ),
    ]
