# Generated by Django 4.2 on 2024-01-09 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_video_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
