# Generated by Django 4.2 on 2024-01-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0005_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('videoMan', models.FileField(upload_to='video/%y')),
                ('videoWoman', models.FileField(upload_to='video/%y')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('title', models.CharField(default='ćwiczenia', max_length=100)),
                ('description', models.TextField(default='opis')),
            ],
        ),
    ]
