# Generated by Django 4.2 on 2023-12-25 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pytania3',
            new_name='Question3',
        ),
        migrations.RenameModel(
            old_name='Pytania4',
            new_name='Question4',
        ),
    ]
