# Generated by Django 4.2 on 2023-12-25 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_rename_pytania3_question3_rename_pytania4_question4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question4',
            old_name='odp1',
            new_name='answ1',
        ),
        migrations.RenameField(
            model_name='question4',
            old_name='odp2',
            new_name='answ2',
        ),
        migrations.RenameField(
            model_name='question4',
            old_name='odp3',
            new_name='answ3',
        ),
        migrations.RenameField(
            model_name='question4',
            old_name='odp4',
            new_name='answ4',
        ),
        migrations.RenameField(
            model_name='question4',
            old_name='dzial',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='question4',
            old_name='pytanie',
            new_name='question',
        ),
    ]
