# Generated by Django 4.2 on 2023-12-25 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_rename_odp1_question3_answ1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question3',
            new_name='Pytania3',
        ),
        migrations.RenameModel(
            old_name='Question4',
            new_name='Pytania4',
        ),
    ]
