# Generated by Django 4.2 on 2024-01-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_heading_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer4',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
