# Generated by Django 4.2 on 2024-01-13 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_remove_question_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='heading',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.heading'),
        ),
    ]
