# Generated by Django 4.2 on 2024-01-13 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_alter_question_answer3_alter_question_answer4'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pytania3',
        ),
        migrations.DeleteModel(
            name='Pytania4',
        ),
    ]
