# Generated by Django 4.2 on 2023-12-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_planner_is_mandatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planner',
            name='is_mandatory',
            field=models.BooleanField(default=True),
        ),
    ]
