# Generated by Django 4.2 on 2023-12-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_planner_is_mandatory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannerMandatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=20)),
                ('value', models.TextField(max_length=400)),
                ('button', models.CharField(max_length=5)),
                ('is_mandatory', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='planner',
            name='is_mandatory',
        ),
    ]
