# Generated by Django 4.2 on 2023-12-28 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_plannermandatory_remove_planner_is_mandatory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannermandatory',
            name='is_mandatory',
        ),
    ]
