# Generated by Django 4.2 on 2024-01-17 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_room_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reward',
        ),
    ]
